version: '3.4'

services:

  fc.codeflix.catalog.fb:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql
    ports:
      - "3360:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - service_catalog

  rabbitmq:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - .docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - .docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 15672:15672
      - 5672:5672

networks:
  service_catalog:
    driver: bridge