# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI do Projeto FC3 Catalog Admin

on:
  push:
    branches: [ "main" , "ci"]
  pull_request:
    branches: [ "main"]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    permissions:
       id-token: write
       contents: read
       checks: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Start containers
      run: docker-compose -f "tests/FC.Codeflix.Catalog.EndToEndTests/docker-compose.yml" up -d --build
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Waits Keycloak
      uses: iFaxity/wait-on-action@v1.2.1
      with:
        resource: http://localhost:8444/realms/fc3-codeflix/.well-known/openid-configuration

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v2.1.1
      if: always()
      with:
        name: Reports Tests
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true

      
